# Generated by Django 4.2.11 on 2024-04-15 14:38

from django.db import migrations, models
import django.db.models.deletion
import uploads.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('file_name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='uploadsDIR/')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField()),
                ('transaction_name', models.CharField(max_length=255)),
                ('withdrawn_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('deposit_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('reference_number', models.CharField(max_length=255)),
                ('closing_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('document', models.ForeignKey(default=uploads.models.get_default_document, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='uploads.uploadedfile')),
            ],
        ),
    ]
